const cwd = './Simulator/Games';
const { exec } = require("child_process");
const { stdout, stderr } = require("process");
const fs = require("fs");

/* 
Function that calls the simulator with files it needs
Sets information abour current round to the file
*/
async function calculate(room, tour){
    const file = `./Simulator/Games/${room}/simul.in`;

    var lines  = await new Promise(resolve => {
        fs.readFile(file, 'utf8', (err, data) => {
            if (err) {
                console.error(err)
                return
            }
            resolve(data);
            
        })
    });

    //Insert current round number at the beginning of the file
    lines = tour + lines.slice(1);


    await new Promise(resolve => {
        
        fs.writeFile(file, lines, err => {
            if(err){  
                console.log(err);
            }
            resolve();
        });
        
    });

    const res = await new Promise((resolve) => {
            const comm = `../../xsimul.out < ./simul.in > ./res`;
            exec(comm, {cwd: cwd + `/${room}`} ,(error, stdout, stderr) => {
            if (error) {
                resolve(`error : ${error}`)
            }
            if (stderr) {
                resolve(`stderr : ${stderr}`)
            }
            resolve("ok");
        });
    });
    return(res);
}

/* 
Creates folders for the new game. Copies all files needed for sim in it
Called with its start
*/
async function newGame(room){
    var comm = "mkdir " + room;
    await new Promise((resolve) => {
            exec(comm, {cwd: cwd}, (error, stdout, stderr) => {
            if(error){
                console.log(error);
            }
            if(stderr) {
                console.log(stderr);
            }
            resolve();
        });
    });
    comm = "cp -p ../Orig/* ./" + room;
    await new Promise((resolve) => {
        exec(comm, {cwd: cwd}, (error, stdout, stderr) => {
            if(error){
                console.log(error);
            }
            if(stderr) {
                console.log(stderr);
            }
            resolve();
        });
    });
}

/* 
Gets player's ut and ub from the file generated by the simulator
*/
async function getLastPlayerStats(room, playerId){
    const file = `./Simulator/Games/${room}/newUtUbP${playerId}.txt`

    console.log("Reading file", file);

    const res = await new Promise(resolve => {
        fs.readFile(file, 'utf8', (err, data) => {
            if (err) {
            console.error(err)
            resolve(-1);
            }
            resolve(data)
        });
    });

    if(res === -1){
        return -1;
    }

    const lines = res.split("\n");
    const stats = {
        ut: parseInt(lines[1].split("         ")[1]),
        ub: parseInt(lines[1].split("         ")[2])
    }
    return stats;
}

/* 
Gets image generated by the simulator. Converts it to 64 byte string to be sended to the client
*/
async function getPlayerGraph(room, playerId){
    const file = `./Simulator/Games/${room}/imgP${playerId}.png`;

    var res = await new Promise(resolve => {
        fs.readFile(file, (err, data) => {
            if(err) {
                console.error(err);
                return
            }
            resolve(data)
        })
    });
    res = "data:image/png;base64,"+ res.toString("base64");
    return res;
}

async function compile(callback){
    const comm = "gfortran ./Simulator/Orig/xsimul.f90 -o ./Simulator/xsimul.out";
    await new Promise((resolve) => {
        exec(comm, (error, stdout, stderr) => {
            if(error){
                console.log("Simulator compilation error:");
                console.log(error);
                process.exit(1);
            }
            if(stderr){
                console.log("Simulator compilation error:");
                console.log(stderr);
                process.exit(1);
            }
            if(stdout){
                console.log("Simulator compilation...")
                console.log(stdout);
            }
            resolve()
        });
    });
    callback();
}


/* 
Function is used by the cleanUp util
Deletes all the tables generated during gaming sessions
*/
async function cleanUp(callback){
    const comm = 'rm -r ./Simulator/Games/*';
    await new Promise((resolve) => {
        exec(comm,  (error, stdout, stderr) => {
            if(error){
                console.log(error);
            }
            if(stderr) {
                console.log(stderr);
            }
            resolve();
        });
    });
    callback();
}

module.exports = {
    calculate,
    newGame,
    getLastPlayerStats,
    getPlayerGraph,
    cleanUp,
    compile
}